// Gyakorlatok ábrája és leírása – az Edzések fül gyakorlat-adatlapja tölti be, első megnyitáskor.
// A fotók a Free Exercise DB-ből valók (github.com/yuhonas/free-exercise-db, public domain / Unlicense):
// gyak/<img>-0.webp a kiinduló, gyak/<img>-1.webp a véghelyzet. A szöveg saját, magyar.
// k: név (ezzel párosítunk), al: más nevek, fo: fő izom, seg: segítő izmok, l: lépések, t: figyelj.
window.EZ_GYAK_INFO = [
{ k:'Mellgép', al:['mellnyomó gép','gépi mellnyomás','chest press'], img:'Leverage_Chest_Press', fo:'Mell', seg:['Tricepsz','Elülső váll'],
  l:['Állítsd be az ülést úgy, hogy a fogantyúk a mellkasod közepe vagy alja magasságában legyenek.',
     'Ülj le, a hátad és a fejed simuljon a támlához, a lapockáidat húzd hátra és le.',
     'Kilégzéssel told előre a fogantyúkat, amíg a karod majdnem kinyúlik.',
     'Egy pillanat szünet után lassan engedd vissza, de ne tedd le a súlyt a sorozat végéig.'],
  t:['A könyököd ne feszüljön ki teljesen a mozdulat végén.','A vállad maradjon lent, ne told előre a lapockáddal.'] },
{ k:'Fekvenyomás', al:['fekvenyomás rúddal','bench press'], img:'Barbell_Bench_Press_-_Medium_Grip', fo:'Mell', seg:['Tricepsz','Elülső váll'],
  l:['Feküdj a padra, a szemed a rúd alatt legyen, a talpad stabilan a földön.',
     'Fogd meg a rudat vállszélességnél kicsit szélesebben, húzd össze és le a lapockáidat.',
     'Emeld ki a rudat, és tartsd nyújtott karral a vállad fölött.',
     'Belégzéssel lassan engedd le a mellkasod közepéig, a könyököd kb. 45°-ban álljon a törzsedhez képest.',
     'Kilégzéssel nyomd vissza a kiinduló helyzetbe.'],
  t:['A farad maradjon a padon, ne emeld meg nyomás közben.','Nehéz súlynál mindig legyen segítőd, vagy használj biztonsági tartót.','Ne pattintsd le a rudat a mellkasodról.'] },
{ k:'Guggolás', al:['guggolás rúddal','squat','hátsó guggolás'], img:'Barbell_Squat', fo:'Négyfejű combizom', seg:['Farizom','Combhajlító','Alsó hát','Vádli'],
  l:['Állj a rúd alá, tedd a trapézizmodra (ne a nyakadra), és fogd meg vállszélességnél szélesebben.',
     'Emeld ki a lábaddal, lépj hátra egyet-kettőt, a lábad vállszélességben, a lábfejed kicsit kifelé.',
     'Belégzéssel, feszes törzzsel ülj le hátra és le, mintha egy székre ülnél, amíg a combod legalább párhuzamos a talajjal.',
     'Kilégzéssel told fel magad a teljes talpadon keresztül a kiinduló helyzetbe.'],
  t:['A térded a lábfejed irányába mozogjon, ne dőljön befelé.','A hátad maradjon egyenes, a mellkasod nézzen előre.','Ketrecben, beállított biztonsági rudakkal guggolj.'] },
{ k:'Felhúzás', al:['felhúzás rúddal','deadlift','klasszikus felhúzás'], img:'Barbell_Deadlift', fo:'Alsó hát', seg:['Farizom','Combhajlító','Négyfejű combizom','Trapéz','Alkar'],
  l:['Állj a rúd elé csípőszélességű terpeszben, a rúd a lábközéped fölött legyen.',
     'Csípőből hajolj le, fogd meg a rudat vállszélességben, a hátad egyenes, a mellkasod kint.',
     'Feszítsd meg a törzsed, és a lábaddal a talajt tolva emeld fel a rudat, a rúd végig a lábad mentén haladjon.',
     'Fent egyenesedj ki teljesen, szorítsd meg a farizmod, majd ugyanazon az úton, kontrolláltan engedd vissza.'],
  t:['A hátad soha ne görbüljön be.','Ne hajolj hátra a mozdulat tetején.','A rúd maradjon közel a testedhez.'] },
{ k:'Lehúzás', al:['lehúzás gépen','széles lehúzás','mellhez húzás','lat pulldown'], img:'Wide-Grip_Lat_Pulldown', fo:'Széles hátizom', seg:['Bicepsz','Hátsó váll','Rombusz'],
  l:['Ülj a géphez, a combodat rögzítsd a párna alatt.',
     'Fogd meg a rudat vállszélességnél szélesebben, dőlj hátra kicsit, a mellkasod legyen kint.',
     'Kilégzéssel húzd a rudat a mellkasod felső részéhez, a könyököd lefelé és hátra mozogjon.',
     'Fent szorítsd össze a lapockáidat, majd lassan engedd vissza nyújtott karig.'],
  t:['Ne a karoddal, hanem a hátaddal húzz: gondolj arra, hogy a könyöködet húzod le.','Ne lendítsd a törzsed hátra-előre.','Ne húzd a rudat a tarkód mögé.'] },
{ k:'Lábtoló', al:['lábtológép','lábtolás','leg press'], img:'Leg_Press', fo:'Négyfejű combizom', seg:['Farizom','Combhajlító','Vádli'],
  l:['Ülj a gépbe, a hátad és a farad simuljon a támlához.',
     'Tedd a lábad a platformra vállszélességben, közepes magasságban.',
     'Told ki a platformot, és oldd ki a biztonsági kart.',
     'Belégzéssel lassan engedd le, amíg a térded kb. 90°-os szöget zár, majd kilégzéssel told vissza a sarkadon keresztül.'],
  t:['A térded fent se feszüljön ki teljesen.','Az alsó pontban a farad ne emelkedjen el a támlától.','A térded ne dőljön befelé.'] },
{ k:'Vállból nyomás', al:['vállnyomás','vállnyomás kézisúlyzóval','shoulder press','nyomás ülve'], img:'Dumbbell_Shoulder_Press', fo:'Elülső váll', seg:['Oldalsó váll','Tricepsz'],
  l:['Ülj egy támlás padra, a kézisúlyzókat emeld vállmagasságba, a tenyered nézzen előre.',
     'Kilégzéssel nyomd a súlyzókat a fejed fölé, amíg a karod majdnem kinyúlik.',
     'Fent egy pillanatra állj meg, majd belégzéssel lassan engedd vissza vállmagasságig.'],
  t:['Ne homoríts: a hátad simuljon a támlához.','A súlyzók fent ne koccanjanak össze.'] },
{ k:'Bicepsz hajlítás', al:['bicepsz','bicepszezés','bicepsz kézisúlyzóval','karhajlítás'], img:'Dumbbell_Bicep_Curl', fo:'Bicepsz', seg:['Alkar'],
  l:['Állj egyenesen, a kézisúlyzókat tartsd a tested mellett, a tenyered nézzen előre.',
     'A felkarod maradjon mozdulatlan, kilégzéssel hajlítsd fel a súlyzókat vállmagasságig.',
     'Fent szorítsd meg a bicepszed, majd lassan engedd vissza.'],
  t:['Ne lendíts a törzseddel.','A könyököd maradjon a törzsed mellett, ne mozogjon előre.'] },
{ k:'Húzódzkodás', al:['húzódzkodás felső fogással','pull-up','pullup'], img:'Pullups', fo:'Széles hátizom', seg:['Bicepsz','Rombusz','Hátsó váll'],
  l:['Fogd meg a rudat felső fogással, vállszélességnél kicsit szélesebben, és lógj nyújtott karral.',
     'Húzd le a lapockáidat, és kilégzéssel húzd fel magad, amíg az állad a rúd fölé ér.',
     'Fent egy pillanatra állj meg, majd belégzéssel lassan engedd le magad nyújtott karig.'],
  t:['Ne lendítsd a lábad.','Minden ismétlésnél menj le teljesen.','Ha még nem megy, kezdd gumiszalaggal vagy gépi segítséggel.'] },
{ k:'Fekvőtámasz', al:['fekvőtámasz padon','push-up','pushup'], img:'Pushups', fo:'Mell', seg:['Tricepsz','Elülső váll','Has'],
  l:['Támaszkodj a kezedre vállszélességnél kicsit szélesebben, a tested fejtől sarokig egy egyenes vonal.',
     'Belégzéssel engedd le magad, amíg a mellkasod majdnem a földhöz ér.',
     'Kilégzéssel told vissza magad nyújtott karig.'],
  t:['A csípőd ne lógjon le és ne emelkedjen fel.','A könyököd kb. 45°-ban álljon, ne teljesen oldalra.','Könnyítés: a térdeden vagy padra támaszkodva.'] },
{ k:'Plank', al:['alkartámasz','deszka','plank tartás'], img:'Plank', fo:'Has', seg:['Ferde hasizom','Alsó hát','Váll'],
  l:['Támaszkodj az alkarodra, a könyököd a vállad alatt legyen.',
     'Nyújtsd hátra a lábad, emeld fel a csípőd, hogy a tested egyenes vonalat alkosson.',
     'Feszítsd meg a hasad és a farizmod, és tartsd a helyzetet egyenletes légzéssel.'],
  t:['A csípőd ne lógjon le.','Ne tartsd vissza a lélegzeted.'] },
{ k:'Evezőgép 500 m', al:['evezőgép','evezés gépen kardió','rower'], img:'Rowing_Stationary', fo:'Négyfejű combizom', seg:['Széles hátizom','Bicepsz','Combhajlító','Farizom'],
  l:['Ülj a gépre, a lábadat rögzítsd a pántokkal, fogd meg a fogantyút.',
     'Kezdd a lábaddal: told el magad, a törzsed kicsit hátradől.',
     'Amikor a lábad kinyúlt, húzd a fogantyút a hasad aljához.',
     'Visszafelé fordítva: először a karod nyújtod, aztán dőlsz előre, végül hajlítod a térded.'],
  t:['Az erő kb. 60%-a a lábadból jön, ne csak a karodból húzz.','A hátad maradjon egyenes.'] },
{ k:'Vállból nyomás váltott karral', al:['váltott karos vállnyomás','váltott vállnyomás'], img:'Standing_Alternating_Dumbbell_Press', fo:'Elülső váll', seg:['Oldalsó váll','Tricepsz','Has'],
  l:['Tartsd a kézisúlyzókat vállmagasságban (ülve vagy állva), a tenyered nézzen előre.',
     'Kilégzéssel nyomd fel az egyik súlyzót, amíg a karod majdnem kinyúlik, a másik marad vállmagasságban.',
     'Lassan engedd vissza, majd a másik karral ismételd.'],
  t:['A törzsed ne dőljön oldalra.','Állva feszítsd meg a hasad és a farizmod.'] },
{ k:'Tárogatás', al:['tárogatás kézisúlyzóval','mellizom tárogatás','fly'], img:'Dumbbell_Flyes', fo:'Mell', seg:['Elülső váll'],
  l:['Feküdj a padra, a kézisúlyzókat tartsd a mellkasod fölött, a tenyereid egymás felé.',
     'Kicsit hajlított könyökkel, belégzéssel ívben engedd szét a karod, amíg nyúlást érzel a mellkasodban.',
     'Kilégzéssel ugyanazon az íven hozd vissza a súlyzókat a mellkasod fölé, mintha egy nagy fát ölelnél át.'],
  t:['A könyököd szöge ne változzon a mozdulat közben.','Ne engedd túl mélyre, a vállad legyen biztonságban.'] },
{ k:'Tricepsznyújtás ülve', al:['tricepsznyújtás','francia nyomás ülve'], img:'Seated_Triceps_Press', fo:'Tricepsz', seg:[],
  l:['Ülj egy padra, egy kézisúlyzót két kézzel fogj meg, és emeld a fejed fölé nyújtott karral.',
     'A felkarod maradjon a füled mellett, belégzéssel engedd a súlyzót a tarkód mögé.',
     'Kilégzéssel nyújtsd ki a karod, és szorítsd meg a tricepszed.'],
  t:['A könyököd ne nyíljon szét oldalra.','Ne homoríts: feszítsd meg a hasad.'] },
{ k:'Oldalemelés', al:['oldalemelés kézisúlyzóval','lateral raise'], img:'Side_Lateral_Raise', fo:'Oldalsó váll', seg:['Elülső váll','Trapéz'],
  l:['Állj egyenesen, a kézisúlyzókat tartsd a tested mellett, a tenyereid befelé.',
     'Kicsit hajlított könyökkel, kilégzéssel emeld oldalra a karod, amíg vállmagasságba ér.',
     'Fent egy pillanatra állj meg, majd lassan engedd vissza.'],
  t:['Ne lendíts: inkább kisebb súlyt használj.','A vállad ne húzódjon fel a füledig.','A könyököd vezesse a mozdulatot, ne a csuklód.'] },
{ k:'Tolódzkodás', al:['tolódzkodás korláton','dips','dip'], img:'Dips_-_Triceps_Version', fo:'Tricepsz', seg:['Mell','Elülső váll'],
  l:['Támaszkodj fel a korlátra nyújtott karral, a tested egyenes.',
     'Belégzéssel hajlítsd a könyököd, és engedd le magad, amíg a felkarod kb. párhuzamos a talajjal.',
     'Kilégzéssel told vissza magad nyújtott karig.'],
  t:['Egyenes testtel inkább a tricepszet, előredőlve inkább a mellet terheled.','Ne menj túl mélyre, ha a vállad fáj.'] },
{ k:'Evezés döntött törzzsel', al:['döntött törzsű evezés','evezés rúddal','bent over row'], img:'Bent_Over_Barbell_Row', fo:'Középső hát', seg:['Széles hátizom','Bicepsz','Hátsó váll','Alsó hát'],
  l:['Fogd meg a rudat felső fogással, vállszélességben, a térded kicsit hajlított.',
     'Hajolj előre csípőből, amíg a törzsed majdnem párhuzamos a talajjal, a hátad egyenes.',
     'Kilégzéssel húzd a rudat a hasad aljához, a könyököd a tested mellett haladjon.',
     'Fent szorítsd össze a lapockáidat, majd lassan engedd le nyújtott karig.'],
  t:['A hátad ne görbüljön be.','Ne emelkedj fel a törzseddel húzás közben.'] },
{ k:'Döntött pados karhajlítás', al:['döntött pados bicepsz','incline curl'], img:'Incline_Dumbbell_Curl', fo:'Bicepsz', seg:['Alkar'],
  l:['Ülj egy kb. 45°-ra döntött padra, a karjaid lógjanak le egyenesen, a tenyered előre.',
     'A felkarod maradjon mozdulatlan, kilégzéssel hajlítsd fel a súlyzókat.',
     'Fent szorítsd meg, majd lassan engedd vissza teljesen nyújtott karig.'],
  t:['A nyújtott helyzet a lényeg: menj le teljesen.','A vállad ne mozduljon előre.'] },
{ k:'Francia rudas bicepsz', al:['ez rudas bicepsz','bicepsz ez rúddal','ez-bar curl'], img:'EZ-Bar_Curl', fo:'Bicepsz', seg:['Alkar'],
  l:['Állj egyenesen, fogd meg az EZ-rudat a külső hajlatnál, alsó fogással.',
     'A könyököd maradjon a tested mellett, kilégzéssel hajlítsd fel a rudat vállmagasságig.',
     'Fent szorítsd meg a bicepszed, majd lassan engedd vissza.'],
  t:['Ne lendíts a derekaddal.','A rúd lefelé is kontrolláltan mozogjon.'] },
{ k:'Kitörés', al:['kitörés kézisúlyzóval','lunge','sétáló kitörés'], img:'Dumbbell_Lunges', fo:'Négyfejű combizom', seg:['Farizom','Combhajlító'],
  l:['Állj egyenesen, a kézisúlyzókat tartsd a tested mellett.',
     'Lépj előre egy nagyot, és engedd le magad, amíg mindkét térded kb. 90°-os.',
     'Az első sarkadon keresztül told vissza magad, vagy lépj tovább a másik lábbal.'],
  t:['Az első térded ne menjen túl a lábujjaidon.','A törzsed maradjon egyenes.','A hátsó térded majdnem érintse a talajt.'] },
{ k:'Román felhúzás', al:['román deadlift','rdl','romanian deadlift'], img:'Romanian_Deadlift', fo:'Combhajlító', seg:['Farizom','Alsó hát'],
  l:['Állj egyenesen, a rudat tartsd vállszélességű felső fogással a combod előtt.',
     'Kicsit hajlított, de rögzített térddel told hátra a csípőd, és engedd le a rudat a combod mentén.',
     'Amikor erős nyúlást érzel a combod hátsó részén (kb. sípcsont közepéig), állj meg.',
     'A csípődet előretolva egyenesedj fel, fent szorítsd meg a farizmod.'],
  t:['A hátad végig egyenes.','Ez nem guggolás: a térded szöge alig változik.'] },
{ k:'Csípőemelés', al:['hip thrust','csípőemelés rúddal','farizom híd'], img:'Barbell_Hip_Thrust', fo:'Farizom', seg:['Combhajlító','Négyfejű combizom'],
  l:['Ülj le, a lapockád támaszkodjon egy padra, a rudat (párnával) tedd a csípődre.',
     'A talpad a földön, térdhajlításban, vállszélességben.',
     'Kilégzéssel told fel a csípőd, amíg a törzsed és a combod egy vonalban van.',
     'Fent szorítsd meg a farizmod, majd lassan engedd vissza.'],
  t:['Fent ne homoríts: a bordáid maradjanak lent.','A sarkadon keresztül tolj.'] },
{ k:'Ülő vádli', al:['ülő vádligép','vádli ülve','seated calf'], img:'Seated_Calf_Raise', fo:'Vádli', seg:[],
  l:['Ülj a gépbe, a párna a combod alsó részén, a lábujjpárnád a lépcső szélén.',
     'Engedd le a sarkad, amíg jó nyúlást érzel a vádlidban.',
     'Kilégzéssel emelkedj lábujjhegyre, amennyire csak tudsz, és fent tartsd meg egy pillanatig.'],
  t:['Teljes mozgástartományban dolgozz, ne rugózz.'] },
{ k:'Lábhajlítás fekve', al:['fekvő lábhajlítás','combhajlító gép','leg curl'], img:'Lying_Leg_Curls', fo:'Combhajlító', seg:['Vádli'],
  l:['Feküdj hasra a gépen, a párna a bokád fölött legyen, a térded épp a pad szélén túl.',
     'Fogd meg a fogantyúkat, a csípőd maradjon a padon.',
     'Kilégzéssel hajlítsd fel a lábad, amennyire tudod, fent szorítsd meg.',
     'Lassan engedd vissza majdnem nyújtott lábig.'],
  t:['A csípőd ne emelkedjen fel.','Visszafelé is kontrolláld a súlyt.'] },
{ k:'Szűk fogású fekvenyomás', al:['szűk fekvenyomás','close grip bench'], img:'Close-Grip_Barbell_Bench_Press', fo:'Tricepsz', seg:['Mell','Elülső váll'],
  l:['Feküdj a padra, fogd meg a rudat vállszélességben (nem szűkebben).',
     'Emeld ki, és belégzéssel engedd le a mellkasod aljáig, a könyököd a törzsed mellett haladjon.',
     'Kilégzéssel nyomd vissza, a tricepszedre koncentrálva.'],
  t:['Túl szűk fogás terheli a csuklót.','A könyököd ne nyíljon szét oldalra.'] },
{ k:'Mellről nyomás állva', al:['katonai nyomás','military press','overhead press','ohp'], img:'Standing_Military_Press', fo:'Elülső váll', seg:['Oldalsó váll','Tricepsz','Has'],
  l:['Állj a rúd elé, fogd meg vállszélességnél kicsit szélesebben, és tedd a mellkasod felső részére.',
     'Feszítsd meg a hasad és a farizmod.',
     'Kilégzéssel nyomd a rudat egyenesen a fejed fölé, a fejed kicsit hátrahúzva, majd fent told előre.',
     'Lassan engedd vissza a mellkasodra.'],
  t:['Ne homoríts és ne dőlj hátra.','A lábaddal ne lendíts, ha szigorú nyomást végzel.'] },
{ k:'Pec deck', al:['pec deck gép','butterfly','pillangó gép','mellgép tárogatás'], img:'Butterfly', fo:'Mell', seg:['Elülső váll'],
  l:['Ülj a gépbe, a hátad simuljon a támlához, a könyököd vagy a kezed a párnákon.',
     'Kilégzéssel hozd össze a karjaidat a mellkasod előtt.',
     'Középen szorítsd meg a mellizmod, majd lassan engedd vissza, amíg nyúlást érzel.'],
  t:['A vállad maradjon lent és hátra.','Ne engedd túl hátra, ha a vállad érzékeny.'] },
{ k:'Tricepsznyújtás fej mögött', al:['tricepsznyújtás fekve','francia nyomás','skull crusher','homlokra engedés'], img:'Lying_Triceps_Press', fo:'Tricepsz', seg:[],
  l:['Feküdj a padra, a rudat (vagy kézisúlyzókat) tartsd nyújtott karral a vállad fölött.',
     'A felkarod maradjon mozdulatlan, belégzéssel hajlítsd a könyököd, és engedd a súlyt a homlokod mögé.',
     'Kilégzéssel nyújtsd ki a karod a kiinduló helyzetbe.'],
  t:['A könyököd ne nyíljon szét.','A felkarod kicsit hátradöntve tartsd, hogy a tricepszed végig feszes maradjon.'] },
{ k:'Rack pull', al:['rack pull','felhúzás állványról','részleges felhúzás'], img:'Rack_Pulls', fo:'Alsó hát', seg:['Farizom','Combhajlító','Trapéz','Alkar'],
  l:['Állítsd a rudat a ketrecben térdmagasságra vagy kicsit alá.',
     'Fogd meg vállszélességben, a hátad egyenes, a mellkasod kint.',
     'Feszítsd meg a törzsed, és a csípődet előretolva emeld fel a rudat teljes kiegyenesedésig.',
     'Kontrolláltan engedd vissza a tartókra.'],
  t:['A hátad soha ne görbüljön be.','Fent ne hajolj hátra, csak egyenesedj ki.'] },
{ k:'Kalapács bicepsz', al:['kalapács','hammer curl'], img:'Hammer_Curls', fo:'Bicepsz', seg:['Alkar','Brachialis'],
  l:['Állj egyenesen, a kézisúlyzókat tartsd a tested mellett, a tenyereid egymás felé.',
     'A könyököd maradjon a törzsed mellett, kilégzéssel hajlítsd fel a súlyzókat.',
     'Fent szorítsd meg, majd lassan engedd vissza.'],
  t:['A csuklód végig semleges fogásban marad.','Ne lendíts.'] },
{ k:'Fordított fogású evezés', al:['alsó fogású evezés','reverse grip row'], img:'Reverse_Grip_Bent-Over_Rows', fo:'Középső hát', seg:['Széles hátizom','Bicepsz','Hátsó váll'],
  l:['Fogd meg a rudat alsó fogással, vállszélességben.',
     'Hajolj előre csípőből, a hátad egyenes, a térded kicsit hajlított.',
     'Kilégzéssel húzd a rudat a hasadhoz, a könyököd a tested mellett.',
     'Fent szorítsd össze a lapockáidat, majd lassan engedd le.'],
  t:['A hátad ne görbüljön be.','Ne rántsd a súlyt.'] },
{ k:'Kábeles kétkezes bicepsz', al:['kábeles bicepsz','csigás bicepsz','cable curl'], img:'Standing_Biceps_Cable_Curl', fo:'Bicepsz', seg:['Alkar'],
  l:['Állj a csiga elé, fogd meg az egyenes rudat alsó fogással, vállszélességben.',
     'A könyököd maradjon a törzsed mellett, kilégzéssel hajlítsd fel a rudat.',
     'Fent szorítsd meg, majd lassan engedd vissza.'],
  t:['A csiga végig feszesen tartja az izmot: lassú visszaengedés.','Ne dőlj hátra.'] },
{ k:'Kábeles evezés', al:['ülő evezés','csigás evezés','seated cable row'], img:'Seated_Cable_Rows', fo:'Középső hát', seg:['Széles hátizom','Bicepsz','Hátsó váll'],
  l:['Ülj a géphez, a talpad a támasztón, a térded kicsit hajlított, fogd meg a fogantyút.',
     'Egyenes háttal ülj fel, a karod nyújtva.',
     'Kilégzéssel húzd a fogantyút a hasadhoz, a könyököd a tested mellett haladjon hátra.',
     'Szorítsd össze a lapockáidat, majd lassan engedd vissza.'],
  t:['Ne lendíts a törzseddel előre-hátra.','A vállad maradjon lent.'] },
{ k:'Bicepsz állva váltott karral', al:['váltott bicepsz','váltott karos bicepsz'], img:'Dumbbell_Alternate_Bicep_Curl', fo:'Bicepsz', seg:['Alkar'],
  l:['Állj egyenesen, a kézisúlyzókat tartsd a tested mellett, a tenyereid befelé.',
     'Az egyik karral hajlítsd fel a súlyzót, közben fordítsd a tenyered felfelé.',
     'Fent szorítsd meg, lassan engedd vissza, majd a másik karral ismételd.'],
  t:['A felkarod ne mozduljon.','Ne lendíts a törzseddel.'] },
{ k:'Vádli lábtolón', al:['vádli a lábtológépen','lábtoló vádli','calf press'], img:'Calf_Press_On_The_Leg_Press_Machine', fo:'Vádli', seg:[],
  l:['Ülj a lábtológépbe, a lábujjpárnádat tedd a platform alsó szélére.',
     'Nyújtott (de nem feszített) lábbal engedd vissza a platformot, amíg nyúlást érzel a vádlidban.',
     'Kilégzéssel told el a platformot a lábujjaiddal, amennyire tudod.'],
  t:['A biztonsági kart hagyd bekapcsolva, ha lehet.','Teljes mozgástartományban dolgozz.'] },
{ k:'Combközelítés ülve', al:['combközelítő gép','adductor','combközelítés'], img:'Thigh_Adductor', fo:'Combközelítő', seg:[],
  l:['Ülj a gépbe, a párnák a combod belső oldalán.',
     'Kilégzéssel told össze a combodat, amíg a párnák összeérnek.',
     'Egy pillanat szünet után lassan engedd vissza.'],
  t:['Ne engedd csapódni a súlyt.','A törzsed maradjon a támlán.'] },
{ k:'Álló vádli', al:['álló vádligép','vádliemelés','standing calf'], img:'Standing_Calf_Raises', fo:'Vádli', seg:[],
  l:['Állj a gépbe, a párnák a válladon, a lábujjpárnád a lépcső szélén.',
     'Engedd le a sarkad, amíg jó nyúlást érzel.',
     'Kilégzéssel emelkedj fel lábujjhegyre, amennyire tudsz, és fent tartsd meg.'],
  t:['A térded maradjon nyújtott, de ne feszített.','Ne rugózz az alsó ponton.'] },
{ k:'Lábnyújtás', al:['lábnyújtó gép','leg extension','combfeszítő gép'], img:'Leg_Extensions', fo:'Négyfejű combizom', seg:[],
  l:['Ülj a gépbe, a párna a bokád elején, a térded a gép tengelyénél legyen.',
     'Kilégzéssel nyújtsd ki a lábad, fent szorítsd meg a combod.',
     'Lassan engedd vissza kb. 90°-os térdszögig.'],
  t:['Ne rúgd fel a súlyt.','A farad maradjon az ülésen.'] },
{ k:'Melltámaszos evezés kézisúlyzóval', al:['melltámaszos evezés','döntött pados evezés','chest supported row'], img:'Dumbbell_Incline_Row', fo:'Középső hát', seg:['Széles hátizom','Hátsó váll','Bicepsz'],
  l:['Feküdj hasra egy kb. 30–45°-os döntött padra, a kézisúlyzók lógjanak le.',
     'Kilégzéssel húzd fel a súlyzókat, a könyököd hátra és felfelé mozogjon.',
     'Fent szorítsd össze a lapockáidat, majd lassan engedd le.'],
  t:['A mellkasod maradjon a padon.','A pad miatt az alsó hátad pihen: a hátadra koncentrálhatsz.'] },
{ k:'Evezés gépen', al:['evező gép hát','gépi evezés','machine row'], img:'Leverage_Iso_Row', fo:'Középső hát', seg:['Széles hátizom','Bicepsz','Hátsó váll'],
  l:['Állítsd be az ülést, a mellkasod támaszkodjon a párnának.',
     'Fogd meg a fogantyúkat nyújtott karral.',
     'Kilégzéssel húzd hátra a fogantyúkat, szorítsd össze a lapockáidat.',
     'Lassan engedd vissza nyújtott karig.'],
  t:['A mellkasod ne váljon el a párnától.','Húzásnál a könyököd vezessen.'] },
{ k:'Hátsó váll tárogatás', al:['hátsó váll','hátsó delta','fordított tárogatás','reverse fly'], img:'Seated_Bent-Over_Rear_Delt_Raise', fo:'Hátsó váll', seg:['Rombusz','Trapéz'],
  l:['Ülj a pad szélére, hajolj előre, amíg a mellkasod majdnem a combodra ér, a súlyzók a lábad mögött.',
     'Kicsit hajlított könyökkel, kilégzéssel emeld oldalra a karod vállmagasságig.',
     'Fent egy pillanatra állj meg, majd lassan engedd vissza.'],
  t:['Kis súllyal, lendítés nélkül.','Ne a lapockáid összehúzásával, hanem a hátsó válladdal emelj.'] },
{ k:'Ferde pados mellnyomógép', al:['ferde mellnyomógép','ferde gépi nyomás','incline chest press'], img:'Leverage_Incline_Chest_Press', fo:'Felső mell', seg:['Elülső váll','Tricepsz'],
  l:['Állítsd be az ülést úgy, hogy a fogantyúk a mellkasod felső részénél legyenek.',
     'A hátad simuljon a támlához, a lapockáid hátra és le.',
     'Kilégzéssel told előre-felfelé a fogantyúkat, majd lassan engedd vissza.'],
  t:['A könyököd ne feszüljön ki.','A vállad maradjon lent.'] },
{ k:'Merevlábas felhúzás', al:['merevlábú felhúzás','stiff legged deadlift'], img:'Stiff-Legged_Barbell_Deadlift', fo:'Combhajlító', seg:['Farizom','Alsó hát'],
  l:['Állj egyenesen, a rudat tartsd felső fogással a combod előtt, a térded szinte nyújtott.',
     'Csípőből hajolj előre, a rúd a lábad mentén haladjon lefelé, amíg nyúlást érzel.',
     'A csípődet előretolva egyenesedj fel, fent szorítsd meg a farizmod.'],
  t:['A hátad egyenes: ha görbül, ne menj lejjebb.','Nehéz súlynál lassan, kontrolláltan.'] },
{ k:'Tricepsz letolás', al:['letolás csigán','tricepsz csigán','tricepsz lehúzás','pushdown'], img:'Triceps_Pushdown', fo:'Tricepsz', seg:[],
  l:['Állj a felső csiga elé, fogd meg a rudat vagy a kötelet felső fogással.',
     'A felkarod a törzsed mellett, a könyököd kb. 90°-ban.',
     'Kilégzéssel told le a rudat, amíg a karod kinyúlik, lent szorítsd meg.',
     'Lassan engedd vissza 90°-ig.'],
  t:['A könyököd ne mozogjon előre-hátra.','Ne dőlj rá a súlyra.'] },
{ k:'Hasprés', al:['has','hasizom','crunch','felülés'], img:'Crunches', fo:'Has', seg:[],
  l:['Feküdj hanyatt, a térded hajlított, a talpad a földön, a kezed a fejed mellett.',
     'Kilégzéssel emeld fel a vállad a földről a hasizmod összehúzásával.',
     'Fent tartsd meg egy pillanatra, majd lassan engedd vissza.'],
  t:['Ne húzd a fejed a kezeddel.','Az alsó hátad maradjon a földön.'] },
{ k:'Ferde pados fekvenyomás', al:['ferde fekvenyomás','incline bench press'], img:'Barbell_Incline_Bench_Press_-_Medium_Grip', fo:'Felső mell', seg:['Elülső váll','Tricepsz'],
  l:['Feküdj egy 30–45°-os döntött padra, fogd meg a rudat vállszélességnél kicsit szélesebben.',
     'Emeld ki, és belégzéssel engedd le a mellkasod felső részéig.',
     'Kilégzéssel nyomd vissza nyújtott karig.'],
  t:['Túl meredek pad már inkább a vállat terheli.','A farad maradjon a padon.'] },
{ k:'Fekvenyomás kézisúlyzóval', al:['kézisúlyzós fekvenyomás','dumbbell bench press'], img:'Dumbbell_Bench_Press', fo:'Mell', seg:['Tricepsz','Elülső váll'],
  l:['Ülj a padra, a súlyzókat a combodon tartva feküdj hátra, és emeld őket a mellkasod mellé.',
     'Kilégzéssel nyomd fel a súlyzókat, amíg a karod majdnem kinyúlik.',
     'Belégzéssel lassan engedd vissza a mellkasod mellé.'],
  t:['A súlyzók fent ne koccanjanak.','Mélyebbre engedheted, mint a rudat, de csak fájdalommentesen.'] },
{ k:'Egykezes evezés', al:['egykezes evezés kézisúlyzóval','egykaros evezés','one arm row'], img:'One-Arm_Dumbbell_Row', fo:'Középső hát', seg:['Széles hátizom','Bicepsz','Hátsó váll'],
  l:['Támaszkodj egy padra az egyik térdeddel és kezeddel, a hátad párhuzamos a talajjal.',
     'A másik kezedben a súlyzó nyújtott karral lóg.',
     'Kilégzéssel húzd a súlyzót a csípőd felé, a könyököd a tested mellett.',
     'Lassan engedd vissza, majd a sorozat után cserélj oldalt.'],
  t:['A törzsed ne forduljon ki húzás közben.','A hátad maradjon egyenes.'] },
{ k:'Vállvonogatás', al:['vállvonás','trapéz','shrug'], img:'Barbell_Shrug', fo:'Trapéz', seg:['Alkar'],
  l:['Állj egyenesen, a rudat tartsd nyújtott karral a combod előtt.',
     'Kilégzéssel emeld a vállad egyenesen a füled felé, amennyire tudod.',
     'Fent tartsd meg egy pillanatra, majd lassan engedd le.'],
  t:['Ne körözz a válladdal, csak fel-le.','A karod maradjon nyújtott.'] },
{ k:'Face pull', al:['arcra húzás','face pull kötéllel'], img:'Face_Pull', fo:'Hátsó váll', seg:['Trapéz','Rombusz'],
  l:['Állítsd a csigát arcmagasságra, fogd meg a kötelet felső fogással.',
     'Lépj hátra, hogy a kötél feszes legyen, a karod nyújtva.',
     'Kilégzéssel húzd a kötelet az arcod felé, a könyököd magasan és oldalra.',
     'Lassan engedd vissza.'],
  t:['A könyököd a kezed fölött vagy azzal egy magasságban legyen.','Kis súllyal, kontrolláltan.'] },
{ k:'Lábemelés függeszkedve', al:['függő lábemelés','lábemelés rúdon','hanging leg raise'], img:'Hanging_Leg_Raise', fo:'Has', seg:['Csípőhajlító','Ferde hasizom'],
  l:['Lógj a húzódzkodó rúdon nyújtott karral.',
     'Kilégzéssel emeld fel a lábad (nyújtva vagy hajlítva), amíg a combod párhuzamos a talajjal vagy magasabbra.',
     'Lassan engedd vissza lengés nélkül.'],
  t:['Ne lendülj: ha lengsz, állj meg és kezdd újra.','Könnyítés: hajlított térddel.'] },
{ k:'Orosz twist', al:['orosz csavarás','russian twist'], img:'Russian_Twist', fo:'Ferde hasizom', seg:['Has'],
  l:['Ülj le, a térded hajlított, dőlj hátra kicsit, a hátad egyenes.',
     'Tarts egy súlyt (vagy csak a kezed) a mellkasod előtt.',
     'Fordítsd a törzsed egyik oldalra, majd a másikra, a súly a csípőd mellé érjen.'],
  t:['A törzsedből fordulj, ne csak a karodból.','Nehezítés: a lábad felemelve.'] },
{ k:'Hiperextenzió', al:['hátfeszítés','hiperextenzió padon','back extension'], img:'Hyperextensions_Back_Extensions', fo:'Alsó hát', seg:['Farizom','Combhajlító'],
  l:['Állj a hiperextenziós padra, a párna a csípőd alatt, a bokád rögzítve.',
     'A kezed a mellkasodon keresztben, egyenes háttal hajolj előre.',
     'Kilégzéssel emelkedj fel, amíg a tested egy vonalban van.'],
  t:['Fent ne homoríts túl.','Lassan, rántás nélkül.'] },
{ k:'Előreemelés', al:['előreemelés kézisúlyzóval','front raise'], img:'Front_Dumbbell_Raise', fo:'Elülső váll', seg:['Oldalsó váll'],
  l:['Állj egyenesen, a súlyzókat tartsd a combod előtt.',
     'Kicsit hajlított könyökkel emeld az egyik vagy mindkét súlyzót előre vállmagasságig.',
     'Lassan engedd vissza.'],
  t:['Ne lendíts a törzseddel.','Vállmagasság fölé nem kell emelni.'] },
{ k:'Goblet guggolás', al:['serleg guggolás','goblet squat'], img:'Goblet_Squat', fo:'Négyfejű combizom', seg:['Farizom','Combhajlító'],
  l:['Tarts egy kézisúlyzót vagy kettlebellt függőlegesen a mellkasod előtt.',
     'Állj vállszélességnél kicsit szélesebben, a lábfejed kicsit kifelé.',
     'Ülj le mélyre, a könyököd a térded között.',
     'A sarkadon keresztül told fel magad.'],
  t:['A mellkasod maradjon kint, a hátad egyenes.','Jó bemelegítő a nagy guggolás előtt.'] },
{ k:'Kettlebell swing', al:['kettlebell lendítés','swing','kb swing'], img:'One-Arm_Kettlebell_Swings', fo:'Farizom', seg:['Combhajlító','Alsó hát','Váll'],
  l:['Állj a kettlebell mögé, vállszélességnél szélesebb terpeszben.',
     'Csípőből hajolj le, fogd meg, és lendítsd hátra a lábad között.',
     'A csípődet erőteljesen előretolva lendítsd a kettlebellt mellmagasságig.',
     'Engedd visszalendülni, és azonnal kezdd a következőt.'],
  t:['Ez csípőmozgás, nem guggolás és nem vállemelés.','A hátad végig egyenes.'] },
{ k:'Arnold nyomás', al:['arnold','arnold press'], img:'Arnold_Dumbbell_Press', fo:'Elülső váll', seg:['Oldalsó váll','Tricepsz'],
  l:['Ülj le, a súlyzókat tartsd a mellkasod előtt, a tenyereid feléd nézzenek.',
     'Nyomás közben fordítsd a tenyered előre, és nyomd a súlyzókat a fejed fölé.',
     'Visszafelé fordítva engedd le a kiinduló helyzetbe.'],
  t:['Folyamatos, egyenletes forgatás.','Ne homoríts.'] },
{ k:'Bolgár guggolás', al:['bolgár','bolgár kitörés','split squat'], img:'Split_Squat_with_Dumbbells', fo:'Négyfejű combizom', seg:['Farizom','Combhajlító'],
  l:['Állj egy pad elé, a hátsó lábfejed tedd a padra.',
     'A súlyzókat tartsd a tested mellett.',
     'Engedd le magad, amíg az első combod párhuzamos a talajjal.',
     'Az első sarkadon keresztül told vissza magad.'],
  t:['Az első térded a lábfejed irányába mozogjon.','A törzsed lehet kicsit előredőlve: ez jobban terheli a farizmot.'] },
{ k:'Állhúzás', al:['húzódzkodás alsó fogással','chin-up','chinup'], img:'Chin-Up', fo:'Széles hátizom', seg:['Bicepsz'],
  l:['Fogd meg a rudat alsó fogással, vállszélességben, és lógj nyújtott karral.',
     'Kilégzéssel húzd fel magad, amíg az állad a rúd fölé ér.',
     'Lassan engedd le magad nyújtott karig.'],
  t:['Ne lendíts.','Az alsó fogás jobban dolgoztatja a bicepszet, mint a felső.'] },
];
